# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Selector_11-12-19.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Selector(object):
    def setupUi(self, Selector):
        Selector.setObjectName("Selector")
        Selector.resize(414, 429)
        Selector.setMouseTracking(False)
        Selector.setTabletTracking(False)
        self.gridLayout = QtWidgets.QGridLayout(Selector)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Selector)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FormLabel_1 = QtWidgets.QLabel(self.tab)
        self.FormLabel_1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FormLabel_1.setTextFormat(QtCore.Qt.AutoText)
        self.FormLabel_1.setObjectName("FormLabel_1")
        self.horizontalLayout_3.addWidget(self.FormLabel_1)
        self.FormComboBox_1 = QtWidgets.QComboBox(self.tab)
        self.FormComboBox_1.setObjectName("FormComboBox_1")
        self.FormComboBox_1.addItem("")
        self.FormComboBox_1.addItem("")
        self.FormComboBox_1.addItem("")
        self.horizontalLayout_3.addWidget(self.FormComboBox_1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.HorizontalSizeParameterLabel_1 = QtWidgets.QLabel(self.tab)
        self.HorizontalSizeParameterLabel_1.setObjectName("HorizontalSizeParameterLabel_1")
        self.horizontalLayout_5.addWidget(self.HorizontalSizeParameterLabel_1)
        self.HorizontalSizeParameterComboBox_1 = QtWidgets.QComboBox(self.tab)
        self.HorizontalSizeParameterComboBox_1.setObjectName("HorizontalSizeParameterComboBox_1")
        self.HorizontalSizeParameterComboBox_1.addItem("")
        self.HorizontalSizeParameterComboBox_1.addItem("")
        self.HorizontalSizeParameterComboBox_1.addItem("")
        self.HorizontalSizeParameterComboBox_1.addItem("")
        self.horizontalLayout_5.addWidget(self.HorizontalSizeParameterComboBox_1)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.VerticalSizeParameterLabel_1 = QtWidgets.QLabel(self.tab)
        self.VerticalSizeParameterLabel_1.setObjectName("VerticalSizeParameterLabel_1")
        self.horizontalLayout_6.addWidget(self.VerticalSizeParameterLabel_1)
        self.VerticalSizeParameterComboBox_1 = QtWidgets.QComboBox(self.tab)
        self.VerticalSizeParameterComboBox_1.setObjectName("VerticalSizeParameterComboBox_1")
        self.VerticalSizeParameterComboBox_1.addItem("")
        self.VerticalSizeParameterComboBox_1.addItem("")
        self.VerticalSizeParameterComboBox_1.addItem("")
        self.VerticalSizeParameterComboBox_1.addItem("")
        self.horizontalLayout_6.addWidget(self.VerticalSizeParameterComboBox_1)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ColorLabel_1 = QtWidgets.QLabel(self.tab)
        self.ColorLabel_1.setObjectName("ColorLabel_1")
        self.horizontalLayout_4.addWidget(self.ColorLabel_1)
        self.ColorComboBox_1 = QtWidgets.QComboBox(self.tab)
        self.ColorComboBox_1.setObjectName("ColorComboBox_1")
        self.ColorComboBox_1.addItem("")
        self.ColorComboBox_1.addItem("")
        self.ColorComboBox_1.addItem("")
        self.ColorComboBox_1.addItem("")
        self.ColorComboBox_1.addItem("")
        self.ColorComboBox_1.addItem("")
        self.ColorComboBox_1.addItem("")
        self.horizontalLayout_4.addWidget(self.ColorComboBox_1)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ColorParameterLabel_1 = QtWidgets.QLabel(self.tab)
        self.ColorParameterLabel_1.setObjectName("ColorParameterLabel_1")
        self.horizontalLayout_2.addWidget(self.ColorParameterLabel_1)
        self.ColorParameterComboBox_1 = QtWidgets.QComboBox(self.tab)
        self.ColorParameterComboBox_1.setObjectName("ColorParameterComboBox_1")
        self.ColorParameterComboBox_1.addItem("")
        self.ColorParameterComboBox_1.addItem("")
        self.ColorParameterComboBox_1.addItem("")
        self.ColorParameterComboBox_1.addItem("")
        self.horizontalLayout_2.addWidget(self.ColorParameterComboBox_1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.FormLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.FormLabel_2.setTextFormat(QtCore.Qt.AutoText)
        self.FormLabel_2.setObjectName("FormLabel_2")
        self.horizontalLayout_7.addWidget(self.FormLabel_2)
        self.FormComboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.FormComboBox_2.setObjectName("FormComboBox_2")
        self.FormComboBox_2.addItem("")
        self.FormComboBox_2.addItem("")
        self.FormComboBox_2.addItem("")
        self.FormComboBox_2.addItem("")
        self.horizontalLayout_7.addWidget(self.FormComboBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.HorizontalSizeParameterLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.HorizontalSizeParameterLabel_2.setObjectName("HorizontalSizeParameterLabel_2")
        self.horizontalLayout_8.addWidget(self.HorizontalSizeParameterLabel_2)
        self.HorizontalSizeParameterComboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.HorizontalSizeParameterComboBox_2.setObjectName("HorizontalSizeParameterComboBox_2")
        self.HorizontalSizeParameterComboBox_2.addItem("")
        self.HorizontalSizeParameterComboBox_2.addItem("")
        self.HorizontalSizeParameterComboBox_2.addItem("")
        self.HorizontalSizeParameterComboBox_2.addItem("")
        self.horizontalLayout_8.addWidget(self.HorizontalSizeParameterComboBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.VerticalSizeParameterLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.VerticalSizeParameterLabel_2.setObjectName("VerticalSizeParameterLabel_2")
        self.horizontalLayout_9.addWidget(self.VerticalSizeParameterLabel_2)
        self.VerticalSizeParameterComboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.VerticalSizeParameterComboBox_2.setObjectName("VerticalSizeParameterComboBox_2")
        self.VerticalSizeParameterComboBox_2.addItem("")
        self.VerticalSizeParameterComboBox_2.addItem("")
        self.VerticalSizeParameterComboBox_2.addItem("")
        self.VerticalSizeParameterComboBox_2.addItem("")
        self.horizontalLayout_9.addWidget(self.VerticalSizeParameterComboBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ColorLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.ColorLabel_2.setObjectName("ColorLabel_2")
        self.horizontalLayout_10.addWidget(self.ColorLabel_2)
        self.ColorComboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.ColorComboBox_2.setObjectName("ColorComboBox_2")
        self.ColorComboBox_2.addItem("")
        self.ColorComboBox_2.addItem("")
        self.ColorComboBox_2.addItem("")
        self.ColorComboBox_2.addItem("")
        self.ColorComboBox_2.addItem("")
        self.ColorComboBox_2.addItem("")
        self.ColorComboBox_2.addItem("")
        self.horizontalLayout_10.addWidget(self.ColorComboBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ColorParameterLabel_2 = QtWidgets.QLabel(self.tab_2)
        self.ColorParameterLabel_2.setObjectName("ColorParameterLabel_2")
        self.horizontalLayout_11.addWidget(self.ColorParameterLabel_2)
        self.ColorParameterComboBox_2 = QtWidgets.QComboBox(self.tab_2)
        self.ColorParameterComboBox_2.setObjectName("ColorParameterComboBox_2")
        self.ColorParameterComboBox_2.addItem("")
        self.ColorParameterComboBox_2.addItem("")
        self.ColorParameterComboBox_2.addItem("")
        self.ColorParameterComboBox_2.addItem("")
        self.horizontalLayout_11.addWidget(self.ColorParameterComboBox_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem11)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.FormLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.FormLabel_3.setTextFormat(QtCore.Qt.AutoText)
        self.FormLabel_3.setObjectName("FormLabel_3")
        self.horizontalLayout_12.addWidget(self.FormLabel_3)
        self.FormComboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.FormComboBox_3.setObjectName("FormComboBox_3")
        self.FormComboBox_3.addItem("")
        self.FormComboBox_3.addItem("")
        self.FormComboBox_3.addItem("")
        self.FormComboBox_3.addItem("")
        self.horizontalLayout_12.addWidget(self.FormComboBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.HorizontalSizeParameterLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.HorizontalSizeParameterLabel_3.setObjectName("HorizontalSizeParameterLabel_3")
        self.horizontalLayout_13.addWidget(self.HorizontalSizeParameterLabel_3)
        self.HorizontalSizeParameterComboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.HorizontalSizeParameterComboBox_3.setObjectName("HorizontalSizeParameterComboBox_3")
        self.HorizontalSizeParameterComboBox_3.addItem("")
        self.HorizontalSizeParameterComboBox_3.addItem("")
        self.HorizontalSizeParameterComboBox_3.addItem("")
        self.HorizontalSizeParameterComboBox_3.addItem("")
        self.horizontalLayout_13.addWidget(self.HorizontalSizeParameterComboBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.VerticalSizeParameterLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.VerticalSizeParameterLabel_3.setObjectName("VerticalSizeParameterLabel_3")
        self.horizontalLayout_14.addWidget(self.VerticalSizeParameterLabel_3)
        self.VerticalSizeParameterComboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.VerticalSizeParameterComboBox_3.setObjectName("VerticalSizeParameterComboBox_3")
        self.VerticalSizeParameterComboBox_3.addItem("")
        self.VerticalSizeParameterComboBox_3.addItem("")
        self.VerticalSizeParameterComboBox_3.addItem("")
        self.VerticalSizeParameterComboBox_3.addItem("")
        self.horizontalLayout_14.addWidget(self.VerticalSizeParameterComboBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem15)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.ColorLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.ColorLabel_3.setObjectName("ColorLabel_3")
        self.horizontalLayout_15.addWidget(self.ColorLabel_3)
        self.ColorComboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.ColorComboBox_3.setObjectName("ColorComboBox_3")
        self.ColorComboBox_3.addItem("")
        self.ColorComboBox_3.addItem("")
        self.ColorComboBox_3.addItem("")
        self.ColorComboBox_3.addItem("")
        self.ColorComboBox_3.addItem("")
        self.ColorComboBox_3.addItem("")
        self.ColorComboBox_3.addItem("")
        self.horizontalLayout_15.addWidget(self.ColorComboBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem16)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ColorParameterLabel_3 = QtWidgets.QLabel(self.tab_3)
        self.ColorParameterLabel_3.setObjectName("ColorParameterLabel_3")
        self.horizontalLayout_16.addWidget(self.ColorParameterLabel_3)
        self.ColorParameterComboBox_3 = QtWidgets.QComboBox(self.tab_3)
        self.ColorParameterComboBox_3.setObjectName("ColorParameterComboBox_3")
        self.ColorParameterComboBox_3.addItem("")
        self.ColorParameterComboBox_3.addItem("")
        self.ColorParameterComboBox_3.addItem("")
        self.ColorParameterComboBox_3.addItem("")
        self.horizontalLayout_16.addWidget(self.ColorParameterComboBox_3)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.FormLabel_4 = QtWidgets.QLabel(self.tab_4)
        self.FormLabel_4.setTextFormat(QtCore.Qt.AutoText)
        self.FormLabel_4.setObjectName("FormLabel_4")
        self.horizontalLayout_17.addWidget(self.FormLabel_4)
        self.FormComboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.FormComboBox_4.setObjectName("FormComboBox_4")
        self.FormComboBox_4.addItem("")
        self.FormComboBox_4.addItem("")
        self.FormComboBox_4.addItem("")
        self.FormComboBox_4.addItem("")
        self.horizontalLayout_17.addWidget(self.FormComboBox_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.HorizontalSizeParameterLabel_4 = QtWidgets.QLabel(self.tab_4)
        self.HorizontalSizeParameterLabel_4.setObjectName("HorizontalSizeParameterLabel_4")
        self.horizontalLayout_18.addWidget(self.HorizontalSizeParameterLabel_4)
        self.HorizontalSizeParameterComboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.HorizontalSizeParameterComboBox_4.setObjectName("HorizontalSizeParameterComboBox_4")
        self.HorizontalSizeParameterComboBox_4.addItem("")
        self.HorizontalSizeParameterComboBox_4.addItem("")
        self.HorizontalSizeParameterComboBox_4.addItem("")
        self.HorizontalSizeParameterComboBox_4.addItem("")
        self.horizontalLayout_18.addWidget(self.HorizontalSizeParameterComboBox_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.VerticalSizeParameterLabel_4 = QtWidgets.QLabel(self.tab_4)
        self.VerticalSizeParameterLabel_4.setObjectName("VerticalSizeParameterLabel_4")
        self.horizontalLayout_19.addWidget(self.VerticalSizeParameterLabel_4)
        self.VerticalSizeParameterComboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.VerticalSizeParameterComboBox_4.setObjectName("VerticalSizeParameterComboBox_4")
        self.VerticalSizeParameterComboBox_4.addItem("")
        self.VerticalSizeParameterComboBox_4.addItem("")
        self.VerticalSizeParameterComboBox_4.addItem("")
        self.VerticalSizeParameterComboBox_4.addItem("")
        self.horizontalLayout_19.addWidget(self.VerticalSizeParameterComboBox_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem21)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.ColorLabel_4 = QtWidgets.QLabel(self.tab_4)
        self.ColorLabel_4.setObjectName("ColorLabel_4")
        self.horizontalLayout_20.addWidget(self.ColorLabel_4)
        self.ColorComboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.ColorComboBox_4.setObjectName("ColorComboBox_4")
        self.ColorComboBox_4.addItem("")
        self.ColorComboBox_4.addItem("")
        self.ColorComboBox_4.addItem("")
        self.ColorComboBox_4.addItem("")
        self.ColorComboBox_4.addItem("")
        self.ColorComboBox_4.addItem("")
        self.ColorComboBox_4.addItem("")
        self.horizontalLayout_20.addWidget(self.ColorComboBox_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem22)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.ColorParameterLabel_4 = QtWidgets.QLabel(self.tab_4)
        self.ColorParameterLabel_4.setObjectName("ColorParameterLabel_4")
        self.horizontalLayout_21.addWidget(self.ColorParameterLabel_4)
        self.ColorParameterComboBox_4 = QtWidgets.QComboBox(self.tab_4)
        self.ColorParameterComboBox_4.setObjectName("ColorParameterComboBox_4")
        self.ColorParameterComboBox_4.addItem("")
        self.ColorParameterComboBox_4.addItem("")
        self.ColorParameterComboBox_4.addItem("")
        self.ColorParameterComboBox_4.addItem("")
        self.horizontalLayout_21.addWidget(self.ColorParameterComboBox_4)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem23)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Selector)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Selector)

    def retranslateUi(self, Selector):
        _translate = QtCore.QCoreApplication.translate
        Selector.setWindowTitle(_translate("Selector", "Selector"))
        self.FormLabel_1.setText(_translate("Selector", "Form :"))
        self.FormComboBox_1.setItemText(0, _translate("Selector", "Ellipse"))
        self.FormComboBox_1.setItemText(1, _translate("Selector", "Rectangle"))
        self.FormComboBox_1.setItemText(2, _translate("Selector", "Triangle"))
        self.HorizontalSizeParameterLabel_1.setText(_translate("Selector", "Horizontal size parameter :"))
        self.HorizontalSizeParameterComboBox_1.setItemText(0, _translate("Selector", "None"))
        self.HorizontalSizeParameterComboBox_1.setItemText(1, _translate("Selector", "RMS"))
        self.HorizontalSizeParameterComboBox_1.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.HorizontalSizeParameterComboBox_1.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.VerticalSizeParameterLabel_1.setText(_translate("Selector", "Vertical size parameter :"))
        self.VerticalSizeParameterComboBox_1.setItemText(0, _translate("Selector", "None"))
        self.VerticalSizeParameterComboBox_1.setItemText(1, _translate("Selector", "RMS"))
        self.VerticalSizeParameterComboBox_1.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.VerticalSizeParameterComboBox_1.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.ColorLabel_1.setText(_translate("Selector", "Color :"))
        self.ColorComboBox_1.setItemText(0, _translate("Selector", "None"))
        self.ColorComboBox_1.setItemText(1, _translate("Selector", "Red"))
        self.ColorComboBox_1.setItemText(2, _translate("Selector", "Blue"))
        self.ColorComboBox_1.setItemText(3, _translate("Selector", "Green"))
        self.ColorComboBox_1.setItemText(4, _translate("Selector", "Yellow"))
        self.ColorComboBox_1.setItemText(5, _translate("Selector", "Grey"))
        self.ColorComboBox_1.setItemText(6, _translate("Selector", "Rainbow"))
        self.ColorParameterLabel_1.setText(_translate("Selector", "Color parameter :"))
        self.ColorParameterComboBox_1.setItemText(0, _translate("Selector", "None"))
        self.ColorParameterComboBox_1.setItemText(1, _translate("Selector", "RMS"))
        self.ColorParameterComboBox_1.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.ColorParameterComboBox_1.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Selector", "Tab 1"))
        self.FormLabel_2.setText(_translate("Selector", "Form :"))
        self.FormComboBox_2.setItemText(0, _translate("Selector", "None"))
        self.FormComboBox_2.setItemText(1, _translate("Selector", "Ellipse"))
        self.FormComboBox_2.setItemText(2, _translate("Selector", "Rectangle"))
        self.FormComboBox_2.setItemText(3, _translate("Selector", "Triangle"))
        self.HorizontalSizeParameterLabel_2.setText(_translate("Selector", "Horizontal size parameter :"))
        self.HorizontalSizeParameterComboBox_2.setItemText(0, _translate("Selector", "None"))
        self.HorizontalSizeParameterComboBox_2.setItemText(1, _translate("Selector", "RMS"))
        self.HorizontalSizeParameterComboBox_2.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.HorizontalSizeParameterComboBox_2.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.VerticalSizeParameterLabel_2.setText(_translate("Selector", "Vertical size parameter :"))
        self.VerticalSizeParameterComboBox_2.setItemText(0, _translate("Selector", "None"))
        self.VerticalSizeParameterComboBox_2.setItemText(1, _translate("Selector", "RMS"))
        self.VerticalSizeParameterComboBox_2.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.VerticalSizeParameterComboBox_2.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.ColorLabel_2.setText(_translate("Selector", "Color :"))
        self.ColorComboBox_2.setItemText(0, _translate("Selector", "None"))
        self.ColorComboBox_2.setItemText(1, _translate("Selector", "Red"))
        self.ColorComboBox_2.setItemText(2, _translate("Selector", "Blue"))
        self.ColorComboBox_2.setItemText(3, _translate("Selector", "Green"))
        self.ColorComboBox_2.setItemText(4, _translate("Selector", "Yellow"))
        self.ColorComboBox_2.setItemText(5, _translate("Selector", "Grey"))
        self.ColorComboBox_2.setItemText(6, _translate("Selector", "Rainbow"))
        self.ColorParameterLabel_2.setText(_translate("Selector", "Color parameter :"))
        self.ColorParameterComboBox_2.setItemText(0, _translate("Selector", "None"))
        self.ColorParameterComboBox_2.setItemText(1, _translate("Selector", "RMS"))
        self.ColorParameterComboBox_2.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.ColorParameterComboBox_2.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Selector", "Tab 2"))
        self.FormLabel_3.setText(_translate("Selector", "Form :"))
        self.FormComboBox_3.setItemText(0, _translate("Selector", "None"))
        self.FormComboBox_3.setItemText(1, _translate("Selector", "Ellipse"))
        self.FormComboBox_3.setItemText(2, _translate("Selector", "Rectangle"))
        self.FormComboBox_3.setItemText(3, _translate("Selector", "Triangle"))
        self.HorizontalSizeParameterLabel_3.setText(_translate("Selector", "Horizontal size parameter :"))
        self.HorizontalSizeParameterComboBox_3.setItemText(0, _translate("Selector", "None"))
        self.HorizontalSizeParameterComboBox_3.setItemText(1, _translate("Selector", "RMS"))
        self.HorizontalSizeParameterComboBox_3.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.HorizontalSizeParameterComboBox_3.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.VerticalSizeParameterLabel_3.setText(_translate("Selector", "Vertical size parameter :"))
        self.VerticalSizeParameterComboBox_3.setItemText(0, _translate("Selector", "None"))
        self.VerticalSizeParameterComboBox_3.setItemText(1, _translate("Selector", "RMS"))
        self.VerticalSizeParameterComboBox_3.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.VerticalSizeParameterComboBox_3.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.ColorLabel_3.setText(_translate("Selector", "Color :"))
        self.ColorComboBox_3.setItemText(0, _translate("Selector", "None"))
        self.ColorComboBox_3.setItemText(1, _translate("Selector", "Red"))
        self.ColorComboBox_3.setItemText(2, _translate("Selector", "Blue"))
        self.ColorComboBox_3.setItemText(3, _translate("Selector", "Green"))
        self.ColorComboBox_3.setItemText(4, _translate("Selector", "Yellow"))
        self.ColorComboBox_3.setItemText(5, _translate("Selector", "Grey"))
        self.ColorComboBox_3.setItemText(6, _translate("Selector", "Rainbow"))
        self.ColorParameterLabel_3.setText(_translate("Selector", "Color parameter :"))
        self.ColorParameterComboBox_3.setItemText(0, _translate("Selector", "None"))
        self.ColorParameterComboBox_3.setItemText(1, _translate("Selector", "RMS"))
        self.ColorParameterComboBox_3.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.ColorParameterComboBox_3.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Selector", "Tab 3"))
        self.FormLabel_4.setText(_translate("Selector", "Form :"))
        self.FormComboBox_4.setItemText(0, _translate("Selector", "None"))
        self.FormComboBox_4.setItemText(1, _translate("Selector", "Ellipse"))
        self.FormComboBox_4.setItemText(2, _translate("Selector", "Rectangle"))
        self.FormComboBox_4.setItemText(3, _translate("Selector", "Triangle"))
        self.HorizontalSizeParameterLabel_4.setText(_translate("Selector", "Horizontal size parameter :"))
        self.HorizontalSizeParameterComboBox_4.setItemText(0, _translate("Selector", "None"))
        self.HorizontalSizeParameterComboBox_4.setItemText(1, _translate("Selector", "RMS"))
        self.HorizontalSizeParameterComboBox_4.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.HorizontalSizeParameterComboBox_4.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.VerticalSizeParameterLabel_4.setText(_translate("Selector", "Vertical size parameter :"))
        self.VerticalSizeParameterComboBox_4.setItemText(0, _translate("Selector", "None"))
        self.VerticalSizeParameterComboBox_4.setItemText(1, _translate("Selector", "RMS"))
        self.VerticalSizeParameterComboBox_4.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.VerticalSizeParameterComboBox_4.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.ColorLabel_4.setText(_translate("Selector", "Color :"))
        self.ColorComboBox_4.setItemText(0, _translate("Selector", "None"))
        self.ColorComboBox_4.setItemText(1, _translate("Selector", "Red"))
        self.ColorComboBox_4.setItemText(2, _translate("Selector", "Blue"))
        self.ColorComboBox_4.setItemText(3, _translate("Selector", "Green"))
        self.ColorComboBox_4.setItemText(4, _translate("Selector", "Yellow"))
        self.ColorComboBox_4.setItemText(5, _translate("Selector", "Grey"))
        self.ColorComboBox_4.setItemText(6, _translate("Selector", "Rainbow"))
        self.ColorParameterLabel_4.setText(_translate("Selector", "Color parameter :"))
        self.ColorParameterComboBox_4.setItemText(0, _translate("Selector", "None"))
        self.ColorParameterComboBox_4.setItemText(1, _translate("Selector", "RMS"))
        self.ColorParameterComboBox_4.setItemText(2, _translate("Selector", "Spectral flatness"))
        self.ColorParameterComboBox_4.setItemText(3, _translate("Selector", "Spectral centroid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Selector", "Tab 4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Selector = QtWidgets.QWidget()
    ui = Ui_Selector()
    ui.setupUi(Selector)
    Selector.show()
    sys.exit(app.exec_())
