# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_modele_03_12_19.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(414, 429)
        Form.setMouseTracking(False)
        Form.setTabletTracking(False)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_2.setContentsMargins(0, -1, 0, -1)
        self.verticalLayout_2.setSpacing(12)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.FormLabel_a = QtWidgets.QLabel(self.tab)
        self.FormLabel_a.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.FormLabel_a.setTextFormat(QtCore.Qt.AutoText)
        self.FormLabel_a.setObjectName("FormLabel_a")
        self.horizontalLayout_3.addWidget(self.FormLabel_a)
        self.SizeParametreComboBox_a = QtWidgets.QComboBox(self.tab)
        self.SizeParametreComboBox_a.setObjectName("SizeParametreComboBox_a")
        self.SizeParametreComboBox_a.addItem("")
        self.SizeParametreComboBox_a.addItem("")
        self.SizeParametreComboBox_a.addItem("")
        self.SizeParametreComboBox_a.addItem("")
        self.SizeParametreComboBox_a.addItem("")
        self.horizontalLayout_3.addWidget(self.SizeParametreComboBox_a)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.SizeParameterLabel_a = QtWidgets.QLabel(self.tab)
        self.SizeParameterLabel_a.setObjectName("SizeParameterLabel_a")
        self.horizontalLayout_5.addWidget(self.SizeParameterLabel_a)
        self.SizeParameterComboBox_a = QtWidgets.QComboBox(self.tab)
        self.SizeParameterComboBox_a.setObjectName("SizeParameterComboBox_a")
        self.SizeParameterComboBox_a.addItem("")
        self.SizeParameterComboBox_a.addItem("")
        self.SizeParameterComboBox_a.addItem("")
        self.SizeParameterComboBox_a.addItem("")
        self.horizontalLayout_5.addWidget(self.SizeParameterComboBox_a)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.PositionParameterLabel_a = QtWidgets.QLabel(self.tab)
        self.PositionParameterLabel_a.setObjectName("PositionParameterLabel_a")
        self.horizontalLayout_6.addWidget(self.PositionParameterLabel_a)
        self.PositionParameterComboBox_a = QtWidgets.QComboBox(self.tab)
        self.PositionParameterComboBox_a.setObjectName("PositionParameterComboBox_a")
        self.PositionParameterComboBox_a.addItem("")
        self.PositionParameterComboBox_a.addItem("")
        self.PositionParameterComboBox_a.addItem("")
        self.PositionParameterComboBox_a.addItem("")
        self.horizontalLayout_6.addWidget(self.PositionParameterComboBox_a)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.ColorLabel_a = QtWidgets.QLabel(self.tab)
        self.ColorLabel_a.setObjectName("ColorLabel_a")
        self.horizontalLayout_4.addWidget(self.ColorLabel_a)
        self.ColorComboBox_a = QtWidgets.QComboBox(self.tab)
        self.ColorComboBox_a.setObjectName("ColorComboBox_a")
        self.ColorComboBox_a.addItem("")
        self.ColorComboBox_a.addItem("")
        self.ColorComboBox_a.addItem("")
        self.ColorComboBox_a.addItem("")
        self.ColorComboBox_a.addItem("")
        self.ColorComboBox_a.addItem("")
        self.ColorComboBox_a.addItem("")
        self.horizontalLayout_4.addWidget(self.ColorComboBox_a)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.ColorParameterLabel_a = QtWidgets.QLabel(self.tab)
        self.ColorParameterLabel_a.setObjectName("ColorParameterLabel_a")
        self.horizontalLayout_2.addWidget(self.ColorParameterLabel_a)
        self.FormComboBox_a = QtWidgets.QComboBox(self.tab)
        self.FormComboBox_a.setObjectName("FormComboBox_a")
        self.FormComboBox_a.addItem("")
        self.FormComboBox_a.addItem("")
        self.FormComboBox_a.addItem("")
        self.FormComboBox_a.addItem("")
        self.horizontalLayout_2.addWidget(self.FormComboBox_a)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem5)
        self.gridLayout_3.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.FormLabel_b = QtWidgets.QLabel(self.tab_2)
        self.FormLabel_b.setTextFormat(QtCore.Qt.AutoText)
        self.FormLabel_b.setObjectName("FormLabel_b")
        self.horizontalLayout_7.addWidget(self.FormLabel_b)
        self.FormComboBox_b = QtWidgets.QComboBox(self.tab_2)
        self.FormComboBox_b.setObjectName("FormComboBox_b")
        self.FormComboBox_b.addItem("")
        self.FormComboBox_b.addItem("")
        self.FormComboBox_b.addItem("")
        self.FormComboBox_b.addItem("")
        self.FormComboBox_b.addItem("")
        self.horizontalLayout_7.addWidget(self.FormComboBox_b)
        self.verticalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.SizeParameterLabel_b = QtWidgets.QLabel(self.tab_2)
        self.SizeParameterLabel_b.setObjectName("SizeParameterLabel_b")
        self.horizontalLayout_8.addWidget(self.SizeParameterLabel_b)
        self.SizeParameterComboBox_b = QtWidgets.QComboBox(self.tab_2)
        self.SizeParameterComboBox_b.setObjectName("SizeParameterComboBox_b")
        self.SizeParameterComboBox_b.addItem("")
        self.SizeParameterComboBox_b.addItem("")
        self.SizeParameterComboBox_b.addItem("")
        self.SizeParameterComboBox_b.addItem("")
        self.horizontalLayout_8.addWidget(self.SizeParameterComboBox_b)
        self.verticalLayout_6.addLayout(self.horizontalLayout_8)
        spacerItem8 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.PositionParameterLabel_b = QtWidgets.QLabel(self.tab_2)
        self.PositionParameterLabel_b.setObjectName("PositionParameterLabel_b")
        self.horizontalLayout_9.addWidget(self.PositionParameterLabel_b)
        self.PositionParameterComboBox_b = QtWidgets.QComboBox(self.tab_2)
        self.PositionParameterComboBox_b.setObjectName("PositionParameterComboBox_b")
        self.PositionParameterComboBox_b.addItem("")
        self.PositionParameterComboBox_b.addItem("")
        self.PositionParameterComboBox_b.addItem("")
        self.PositionParameterComboBox_b.addItem("")
        self.horizontalLayout_9.addWidget(self.PositionParameterComboBox_b)
        self.verticalLayout_6.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.ColorLabel_b = QtWidgets.QLabel(self.tab_2)
        self.ColorLabel_b.setObjectName("ColorLabel_b")
        self.horizontalLayout_10.addWidget(self.ColorLabel_b)
        self.ColorComboBox_b = QtWidgets.QComboBox(self.tab_2)
        self.ColorComboBox_b.setObjectName("ColorComboBox_b")
        self.ColorComboBox_b.addItem("")
        self.ColorComboBox_b.addItem("")
        self.ColorComboBox_b.addItem("")
        self.ColorComboBox_b.addItem("")
        self.ColorComboBox_b.addItem("")
        self.ColorComboBox_b.addItem("")
        self.ColorComboBox_b.addItem("")
        self.horizontalLayout_10.addWidget(self.ColorComboBox_b)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.ColorParameterLabel_b = QtWidgets.QLabel(self.tab_2)
        self.ColorParameterLabel_b.setObjectName("ColorParameterLabel_b")
        self.horizontalLayout_11.addWidget(self.ColorParameterLabel_b)
        self.ColorParameterComboBox_b = QtWidgets.QComboBox(self.tab_2)
        self.ColorParameterComboBox_b.setObjectName("ColorParameterComboBox_b")
        self.ColorParameterComboBox_b.addItem("")
        self.ColorParameterComboBox_b.addItem("")
        self.ColorParameterComboBox_b.addItem("")
        self.ColorParameterComboBox_b.addItem("")
        self.horizontalLayout_11.addWidget(self.ColorParameterComboBox_b)
        self.verticalLayout_6.addLayout(self.horizontalLayout_11)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_6.addItem(spacerItem11)
        self.gridLayout_4.addLayout(self.verticalLayout_6, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem12)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.FormLabel_c = QtWidgets.QLabel(self.tab_3)
        self.FormLabel_c.setTextFormat(QtCore.Qt.AutoText)
        self.FormLabel_c.setObjectName("FormLabel_c")
        self.horizontalLayout_12.addWidget(self.FormLabel_c)
        self.FormComboBox_c = QtWidgets.QComboBox(self.tab_3)
        self.FormComboBox_c.setObjectName("FormComboBox_c")
        self.FormComboBox_c.addItem("")
        self.FormComboBox_c.addItem("")
        self.FormComboBox_c.addItem("")
        self.FormComboBox_c.addItem("")
        self.FormComboBox_c.addItem("")
        self.horizontalLayout_12.addWidget(self.FormComboBox_c)
        self.verticalLayout_5.addLayout(self.horizontalLayout_12)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem13)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.SizeParameterLabel_c = QtWidgets.QLabel(self.tab_3)
        self.SizeParameterLabel_c.setObjectName("SizeParameterLabel_c")
        self.horizontalLayout_13.addWidget(self.SizeParameterLabel_c)
        self.SizeParameterComboBox_c = QtWidgets.QComboBox(self.tab_3)
        self.SizeParameterComboBox_c.setObjectName("SizeParameterComboBox_c")
        self.SizeParameterComboBox_c.addItem("")
        self.SizeParameterComboBox_c.addItem("")
        self.SizeParameterComboBox_c.addItem("")
        self.SizeParameterComboBox_c.addItem("")
        self.horizontalLayout_13.addWidget(self.SizeParameterComboBox_c)
        self.verticalLayout_5.addLayout(self.horizontalLayout_13)
        spacerItem14 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem14)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.PositionParameterLabel_c = QtWidgets.QLabel(self.tab_3)
        self.PositionParameterLabel_c.setObjectName("PositionParameterLabel_c")
        self.horizontalLayout_14.addWidget(self.PositionParameterLabel_c)
        self.PositionParameterComboBox_c = QtWidgets.QComboBox(self.tab_3)
        self.PositionParameterComboBox_c.setObjectName("PositionParameterComboBox_c")
        self.PositionParameterComboBox_c.addItem("")
        self.PositionParameterComboBox_c.addItem("")
        self.PositionParameterComboBox_c.addItem("")
        self.PositionParameterComboBox_c.addItem("")
        self.horizontalLayout_14.addWidget(self.PositionParameterComboBox_c)
        self.verticalLayout_5.addLayout(self.horizontalLayout_14)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem15)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.ColorLabel_c = QtWidgets.QLabel(self.tab_3)
        self.ColorLabel_c.setObjectName("ColorLabel_c")
        self.horizontalLayout_15.addWidget(self.ColorLabel_c)
        self.ColorComboBox_c = QtWidgets.QComboBox(self.tab_3)
        self.ColorComboBox_c.setObjectName("ColorComboBox_c")
        self.ColorComboBox_c.addItem("")
        self.ColorComboBox_c.addItem("")
        self.ColorComboBox_c.addItem("")
        self.ColorComboBox_c.addItem("")
        self.ColorComboBox_c.addItem("")
        self.ColorComboBox_c.addItem("")
        self.ColorComboBox_c.addItem("")
        self.horizontalLayout_15.addWidget(self.ColorComboBox_c)
        self.verticalLayout_5.addLayout(self.horizontalLayout_15)
        spacerItem16 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem16)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.ColorParameterLabel_c = QtWidgets.QLabel(self.tab_3)
        self.ColorParameterLabel_c.setObjectName("ColorParameterLabel_c")
        self.horizontalLayout_16.addWidget(self.ColorParameterLabel_c)
        self.ColorParameterComboBox_c = QtWidgets.QComboBox(self.tab_3)
        self.ColorParameterComboBox_c.setObjectName("ColorParameterComboBox_c")
        self.ColorParameterComboBox_c.addItem("")
        self.ColorParameterComboBox_c.addItem("")
        self.ColorParameterComboBox_c.addItem("")
        self.ColorParameterComboBox_c.addItem("")
        self.horizontalLayout_16.addWidget(self.ColorParameterComboBox_c)
        self.verticalLayout_5.addLayout(self.horizontalLayout_16)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem17)
        self.gridLayout_5.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.tab_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem18)
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.FormLabel_d = QtWidgets.QLabel(self.tab_4)
        self.FormLabel_d.setTextFormat(QtCore.Qt.AutoText)
        self.FormLabel_d.setObjectName("FormLabel_d")
        self.horizontalLayout_17.addWidget(self.FormLabel_d)
        self.FormComboBox_d = QtWidgets.QComboBox(self.tab_4)
        self.FormComboBox_d.setObjectName("FormComboBox_d")
        self.FormComboBox_d.addItem("")
        self.FormComboBox_d.addItem("")
        self.FormComboBox_d.addItem("")
        self.FormComboBox_d.addItem("")
        self.FormComboBox_d.addItem("")
        self.horizontalLayout_17.addWidget(self.FormComboBox_d)
        self.verticalLayout_7.addLayout(self.horizontalLayout_17)
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem19)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.SizeParameterLabel_d = QtWidgets.QLabel(self.tab_4)
        self.SizeParameterLabel_d.setObjectName("SizeParameterLabel_d")
        self.horizontalLayout_18.addWidget(self.SizeParameterLabel_d)
        self.SizeParameterComboBox_d = QtWidgets.QComboBox(self.tab_4)
        self.SizeParameterComboBox_d.setObjectName("SizeParameterComboBox_d")
        self.SizeParameterComboBox_d.addItem("")
        self.SizeParameterComboBox_d.addItem("")
        self.SizeParameterComboBox_d.addItem("")
        self.SizeParameterComboBox_d.addItem("")
        self.horizontalLayout_18.addWidget(self.SizeParameterComboBox_d)
        self.verticalLayout_7.addLayout(self.horizontalLayout_18)
        spacerItem20 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem20)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.PositionParameterLabel_d = QtWidgets.QLabel(self.tab_4)
        self.PositionParameterLabel_d.setObjectName("PositionParameterLabel_d")
        self.horizontalLayout_19.addWidget(self.PositionParameterLabel_d)
        self.PositionParameterComboBox_d = QtWidgets.QComboBox(self.tab_4)
        self.PositionParameterComboBox_d.setObjectName("PositionParameterComboBox_d")
        self.PositionParameterComboBox_d.addItem("")
        self.PositionParameterComboBox_d.addItem("")
        self.PositionParameterComboBox_d.addItem("")
        self.PositionParameterComboBox_d.addItem("")
        self.horizontalLayout_19.addWidget(self.PositionParameterComboBox_d)
        self.verticalLayout_7.addLayout(self.horizontalLayout_19)
        spacerItem21 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem21)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.ColorLabel_d = QtWidgets.QLabel(self.tab_4)
        self.ColorLabel_d.setObjectName("ColorLabel_d")
        self.horizontalLayout_20.addWidget(self.ColorLabel_d)
        self.ColorComboBox_d = QtWidgets.QComboBox(self.tab_4)
        self.ColorComboBox_d.setObjectName("ColorComboBox_d")
        self.ColorComboBox_d.addItem("")
        self.ColorComboBox_d.addItem("")
        self.ColorComboBox_d.addItem("")
        self.ColorComboBox_d.addItem("")
        self.ColorComboBox_d.addItem("")
        self.ColorComboBox_d.addItem("")
        self.ColorComboBox_d.addItem("")
        self.horizontalLayout_20.addWidget(self.ColorComboBox_d)
        self.verticalLayout_7.addLayout(self.horizontalLayout_20)
        spacerItem22 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem22)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.ColorParameterLabel_d = QtWidgets.QLabel(self.tab_4)
        self.ColorParameterLabel_d.setObjectName("ColorParameterLabel_d")
        self.horizontalLayout_21.addWidget(self.ColorParameterLabel_d)
        self.ColorParameterComboBox_d = QtWidgets.QComboBox(self.tab_4)
        self.ColorParameterComboBox_d.setObjectName("ColorParameterComboBox_d")
        self.ColorParameterComboBox_d.addItem("")
        self.ColorParameterComboBox_d.addItem("")
        self.ColorParameterComboBox_d.addItem("")
        self.ColorParameterComboBox_d.addItem("")
        self.horizontalLayout_21.addWidget(self.ColorParameterComboBox_d)
        self.verticalLayout_7.addLayout(self.horizontalLayout_21)
        spacerItem23 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_7.addItem(spacerItem23)
        self.gridLayout_6.addLayout(self.verticalLayout_7, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_4, "")
        self.verticalLayout_2.addWidget(self.tabWidget)
        self.gridLayout.addLayout(self.verticalLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.FormLabel_a.setText(_translate("Form", "Form :"))
        self.SizeParametreComboBox_a.setItemText(0, _translate("Form", "None"))
        self.SizeParametreComboBox_a.setItemText(1, _translate("Form", "Square"))
        self.SizeParametreComboBox_a.setItemText(2, _translate("Form", "Circle"))
        self.SizeParametreComboBox_a.setItemText(3, _translate("Form", "Ellipse"))
        self.SizeParametreComboBox_a.setItemText(4, _translate("Form", "Triangle"))
        self.SizeParameterLabel_a.setText(_translate("Form", "Size parameter :"))
        self.SizeParameterComboBox_a.setItemText(0, _translate("Form", "None"))
        self.SizeParameterComboBox_a.setItemText(1, _translate("Form", "RMS"))
        self.SizeParameterComboBox_a.setItemText(2, _translate("Form", "Spectral flatness"))
        self.SizeParameterComboBox_a.setItemText(3, _translate("Form", "Spectral centroid"))
        self.PositionParameterLabel_a.setText(_translate("Form", "Position parameter :"))
        self.PositionParameterComboBox_a.setItemText(0, _translate("Form", "None"))
        self.PositionParameterComboBox_a.setItemText(1, _translate("Form", "RMS"))
        self.PositionParameterComboBox_a.setItemText(2, _translate("Form", "Spectral flatness"))
        self.PositionParameterComboBox_a.setItemText(3, _translate("Form", "Spectral centroid"))
        self.ColorLabel_a.setText(_translate("Form", "Color :"))
        self.ColorComboBox_a.setItemText(0, _translate("Form", "None"))
        self.ColorComboBox_a.setItemText(1, _translate("Form", "Red"))
        self.ColorComboBox_a.setItemText(2, _translate("Form", "Blue"))
        self.ColorComboBox_a.setItemText(3, _translate("Form", "Green"))
        self.ColorComboBox_a.setItemText(4, _translate("Form", "Yellow"))
        self.ColorComboBox_a.setItemText(5, _translate("Form", "Grey"))
        self.ColorComboBox_a.setItemText(6, _translate("Form", "Rainbow"))
        self.ColorParameterLabel_a.setText(_translate("Form", "Color parameter :"))
        self.FormComboBox_a.setItemText(0, _translate("Form", "None"))
        self.FormComboBox_a.setItemText(1, _translate("Form", "RMS"))
        self.FormComboBox_a.setItemText(2, _translate("Form", "Spectral flatness"))
        self.FormComboBox_a.setItemText(3, _translate("Form", "Spectral centroid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.FormLabel_b.setText(_translate("Form", "Form :"))
        self.FormComboBox_b.setItemText(0, _translate("Form", "None"))
        self.FormComboBox_b.setItemText(1, _translate("Form", "Square"))
        self.FormComboBox_b.setItemText(2, _translate("Form", "Circle"))
        self.FormComboBox_b.setItemText(3, _translate("Form", "Ellipse"))
        self.FormComboBox_b.setItemText(4, _translate("Form", "Triangle"))
        self.SizeParameterLabel_b.setText(_translate("Form", "Size parameter :"))
        self.SizeParameterComboBox_b.setItemText(0, _translate("Form", "None"))
        self.SizeParameterComboBox_b.setItemText(1, _translate("Form", "RMS"))
        self.SizeParameterComboBox_b.setItemText(2, _translate("Form", "Spectral flatness"))
        self.SizeParameterComboBox_b.setItemText(3, _translate("Form", "Spectral centroid"))
        self.PositionParameterLabel_b.setText(_translate("Form", "Position parameter :"))
        self.PositionParameterComboBox_b.setItemText(0, _translate("Form", "None"))
        self.PositionParameterComboBox_b.setItemText(1, _translate("Form", "RMS"))
        self.PositionParameterComboBox_b.setItemText(2, _translate("Form", "Spectral flatness"))
        self.PositionParameterComboBox_b.setItemText(3, _translate("Form", "Spectral centroid"))
        self.ColorLabel_b.setText(_translate("Form", "Color :"))
        self.ColorComboBox_b.setItemText(0, _translate("Form", "None"))
        self.ColorComboBox_b.setItemText(1, _translate("Form", "Red"))
        self.ColorComboBox_b.setItemText(2, _translate("Form", "Blue"))
        self.ColorComboBox_b.setItemText(3, _translate("Form", "Green"))
        self.ColorComboBox_b.setItemText(4, _translate("Form", "Yellow"))
        self.ColorComboBox_b.setItemText(5, _translate("Form", "Grey"))
        self.ColorComboBox_b.setItemText(6, _translate("Form", "Rainbow"))
        self.ColorParameterLabel_b.setText(_translate("Form", "Color parameter :"))
        self.ColorParameterComboBox_b.setItemText(0, _translate("Form", "None"))
        self.ColorParameterComboBox_b.setItemText(1, _translate("Form", "RMS"))
        self.ColorParameterComboBox_b.setItemText(2, _translate("Form", "Spectral flatness"))
        self.ColorParameterComboBox_b.setItemText(3, _translate("Form", "Spectral centroid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.FormLabel_c.setText(_translate("Form", "Form :"))
        self.FormComboBox_c.setItemText(0, _translate("Form", "None"))
        self.FormComboBox_c.setItemText(1, _translate("Form", "Square"))
        self.FormComboBox_c.setItemText(2, _translate("Form", "Circle"))
        self.FormComboBox_c.setItemText(3, _translate("Form", "Ellipse"))
        self.FormComboBox_c.setItemText(4, _translate("Form", "Triangle"))
        self.SizeParameterLabel_c.setText(_translate("Form", "Size parameter :"))
        self.SizeParameterComboBox_c.setItemText(0, _translate("Form", "None"))
        self.SizeParameterComboBox_c.setItemText(1, _translate("Form", "RMS"))
        self.SizeParameterComboBox_c.setItemText(2, _translate("Form", "Spectral flatness"))
        self.SizeParameterComboBox_c.setItemText(3, _translate("Form", "Spectral centroid"))
        self.PositionParameterLabel_c.setText(_translate("Form", "Position parameter :"))
        self.PositionParameterComboBox_c.setItemText(0, _translate("Form", "None"))
        self.PositionParameterComboBox_c.setItemText(1, _translate("Form", "RMS"))
        self.PositionParameterComboBox_c.setItemText(2, _translate("Form", "Spectral flatness"))
        self.PositionParameterComboBox_c.setItemText(3, _translate("Form", "Spectral centroid"))
        self.ColorLabel_c.setText(_translate("Form", "Color :"))
        self.ColorComboBox_c.setItemText(0, _translate("Form", "None"))
        self.ColorComboBox_c.setItemText(1, _translate("Form", "Red"))
        self.ColorComboBox_c.setItemText(2, _translate("Form", "Blue"))
        self.ColorComboBox_c.setItemText(3, _translate("Form", "Green"))
        self.ColorComboBox_c.setItemText(4, _translate("Form", "Yellow"))
        self.ColorComboBox_c.setItemText(5, _translate("Form", "Grey"))
        self.ColorComboBox_c.setItemText(6, _translate("Form", "Rainbow"))
        self.ColorParameterLabel_c.setText(_translate("Form", "Color parameter :"))
        self.ColorParameterComboBox_c.setItemText(0, _translate("Form", "None"))
        self.ColorParameterComboBox_c.setItemText(1, _translate("Form", "RMS"))
        self.ColorParameterComboBox_c.setItemText(2, _translate("Form", "Spectral flatness"))
        self.ColorParameterComboBox_c.setItemText(3, _translate("Form", "Spectral centroid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Tab 3"))
        self.FormLabel_d.setText(_translate("Form", "Form :"))
        self.FormComboBox_d.setItemText(0, _translate("Form", "None"))
        self.FormComboBox_d.setItemText(1, _translate("Form", "Square"))
        self.FormComboBox_d.setItemText(2, _translate("Form", "Circle"))
        self.FormComboBox_d.setItemText(3, _translate("Form", "Ellipse"))
        self.FormComboBox_d.setItemText(4, _translate("Form", "Triangle"))
        self.SizeParameterLabel_d.setText(_translate("Form", "Size parameter :"))
        self.SizeParameterComboBox_d.setItemText(0, _translate("Form", "None"))
        self.SizeParameterComboBox_d.setItemText(1, _translate("Form", "RMS"))
        self.SizeParameterComboBox_d.setItemText(2, _translate("Form", "Spectral flatness"))
        self.SizeParameterComboBox_d.setItemText(3, _translate("Form", "Spectral centroid"))
        self.PositionParameterLabel_d.setText(_translate("Form", "Position parameter :"))
        self.PositionParameterComboBox_d.setItemText(0, _translate("Form", "None"))
        self.PositionParameterComboBox_d.setItemText(1, _translate("Form", "RMS"))
        self.PositionParameterComboBox_d.setItemText(2, _translate("Form", "Spectral flatness"))
        self.PositionParameterComboBox_d.setItemText(3, _translate("Form", "Spectral centroid"))
        self.ColorLabel_d.setText(_translate("Form", "Color :"))
        self.ColorComboBox_d.setItemText(0, _translate("Form", "None"))
        self.ColorComboBox_d.setItemText(1, _translate("Form", "Red"))
        self.ColorComboBox_d.setItemText(2, _translate("Form", "Blue"))
        self.ColorComboBox_d.setItemText(3, _translate("Form", "Green"))
        self.ColorComboBox_d.setItemText(4, _translate("Form", "Yellow"))
        self.ColorComboBox_d.setItemText(5, _translate("Form", "Grey"))
        self.ColorComboBox_d.setItemText(6, _translate("Form", "Rainbow"))
        self.ColorParameterLabel_d.setText(_translate("Form", "Color parameter :"))
        self.ColorParameterComboBox_d.setItemText(0, _translate("Form", "None"))
        self.ColorParameterComboBox_d.setItemText(1, _translate("Form", "RMS"))
        self.ColorParameterComboBox_d.setItemText(2, _translate("Form", "Spectral flatness"))
        self.ColorParameterComboBox_d.setItemText(3, _translate("Form", "Spectral centroid"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Form", "Tab 4"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

